version: '3.5'

services:  
  CourseWork_DB:
    container_name: CourseWork_DB
    image: postgres:15.4-alpine
    restart: always
    ports:
      - "5432:5432"
    expose:
      - 5432
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
